runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: ssl
  version: latest

# [START handlers]
handlers:
- url: /static
  static_dir: app/static
- url: /.*
  script: main.app
# [END handlers]

